TILE_SIZE = 52
SPRITE_SIZE = 104
SCALE = 16
SCREEN_WIDTH = TILE_SIZE*SCALE
SCREEN_HEIGHT = TILE_SIZE*SCALE

PLAYER_SPRITE_SIZE_X = 288
PLAYER_SPRITE_SIZE_Y = 128

BULLET_SPRITE_SIZE_X = 48
BULLET_SPRITE_SIZE_Y = 32

ENEMY_SPRTE_SIZE_X = 23
ENEMY_SPRTE_SIZE_Y = 31

ENEMY_SPRITE_MULTIPLIER = 3.3

RIGHT = 0
LEFT = 1

RESOURCE_PATH = "./resources/"
SPRITES_PATH = RESOURCE_PATH + "sprites/"

PLAYER_CENTER = (SCREEN_WIDTH/2,SCREEN_HEIGHT/2 - (TILE_SIZE + TILE_SIZE/2) + 4)
PLAYER_HITBOX = (250,175,-500,-175)

RESPAWN_COOLDOWN = 1500
RESPAWN_PROB = 0.1
ENEMY_VELOCITY = 40
BULLET_VELOCITY = 150

FPS = 60