TILE_SIZE = 52
SPRITE_SIZE = 104
SCALE = 16
SCREEN_WIDTH = TILE_SIZE*SCALE
SCREEN_HEIGHT = TILE_SIZE*SCALE
DIAMETER = SCREEN_WIDTH
CENTER_X = SCREEN_WIDTH/2
CENTER_Y = SCREEN_HEIGHT/2

PLAYER_SPRITE_SIZE_X = 288
PLAYER_SPRITE_SIZE_Y = 128

BULLET_SPRITE_SIZE_X = 48
BULLET_SPRITE_SIZE_Y = 32

ENEMY_SPRTE_SIZE_X = 24
ENEMY_SPRTE_SIZE_Y = 32

ENEMY_SPRITE_MULTIPLIER = 3.3

RIGHT = 0
LEFT = 1
TOP = 2
BOTTOM = 3

RESOURCE_PATH = "./resources/"
SPRITES_PATH = RESOURCE_PATH + "sprites/"

PLAYER_CENTER = (SCREEN_WIDTH/2,SCREEN_HEIGHT/2 - (TILE_SIZE + TILE_SIZE/2) + 4)
PLAYER_HITBOX = (250,175,-500,-175)

RESPAWN_COOLDOWN = 1250
RESPAWN_PROB = 0.1
ENEMY_VELOCITY = 2
BULLET_VELOCITY = 5
ROTATE_VELOCITY = 2

SHOOT_COOLDOWN = 0.75
ROTATE_COOLDOWN = 2

MAX_ENEMIES = 4

TRAINING = False

SPEED = 1000

# DANGER ZONES

DANGER_ZONE_LEFT_0 = 0
DANGER_ZONE_RIGHT_0 = SCREEN_WIDTH

DANGER_ZONE_LEFT_1 = SCREEN_WIDTH/16 + TILE_SIZE*0
DANGER_ZONE_RIGHT_1 = SCREEN_WIDTH - SCREEN_WIDTH/16 - TILE_SIZE*0

DANGER_ZONE_LEFT_2 = SCREEN_WIDTH/16 + TILE_SIZE*1
DANGER_ZONE_RIGHT_2 = SCREEN_WIDTH - SCREEN_WIDTH/16 - TILE_SIZE*1

DANGER_ZONE_LEFT_3 = SCREEN_WIDTH/16 + TILE_SIZE*2
DANGER_ZONE_RIGHT_3 = SCREEN_WIDTH - SCREEN_WIDTH/16 - TILE_SIZE*2

DANGER_ZONE_LEFT_4 = SCREEN_WIDTH/16 + TILE_SIZE*3
DANGER_ZONE_RIGHT_4 = SCREEN_WIDTH - SCREEN_WIDTH/16 - TILE_SIZE*3

FPS = SPEED if TRAINING else 144
TARGET_FPS = 1 if TRAINING else 60



